[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "qekit"
version = "0.1.0"
dependencies = [
    "questionary",
    "numpy",
    "spglib",
    "seekpath",
    "ase"
]

[project.scripts]
qekit = "qekit:main"  # Connects terminal command to the code
