[[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "qekit"
version = "0.1.0"
dependencies = [
    "questionary",
    "numpy",
    "spglib",
    "seekpath",
    "ase"
]

[project.scripts]
qekit = "qekit:main"

# --- ADD THIS SECTION ---
[tool.setuptools]
py-modules = ["qekit"]

[tool.setuptools.packages.find]
where = ["."]
include = ["modules*", "utils*"]
